-- Table des Utilisateurs
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pseudo TEXT UNIQUE NOT NULL,
  pin_code TEXT NOT NULL,
  total_score INT DEFAULT 0,
  role TEXT DEFAULT 'SUPPORTER',
  avatar_emoji TEXT DEFAULT '🏀',
  theme TEXT DEFAULT 'dark',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Migrations sécurisées pour ajouter la colonne si la table existe déjà
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS theme TEXT DEFAULT 'dark';

-- Table des Matchs
CREATE TABLE IF NOT EXISTS public.matches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  opponent TEXT NOT NULL,
  date_time TIMESTAMPTZ NOT NULL,
  is_home BOOLEAN NOT NULL DEFAULT TRUE,
  score_bcsn INT NULL,
  score_opponent INT NULL,
  status TEXT DEFAULT 'PENDING',
  matchday INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table des Pronostics
CREATE TABLE IF NOT EXISTS public.predictions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
  match_id BIGINT REFERENCES public.matches(id) ON DELETE CASCADE,
  predicted_bcsn INT NOT NULL,
  predicted_opponent INT NOT NULL,
  points_earned INT DEFAULT 0,
  CONSTRAINT unique_user_match UNIQUE(user_id, match_id)
);

-- Table des Abonnements Push Notifications
CREATE TABLE IF NOT EXISTS public.push_subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
  endpoint TEXT NOT NULL UNIQUE,
  p256dh TEXT NOT NULL,
  auth TEXT NOT NULL,
  user_agent TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Activer RLS et autoriser l'accès public
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.predictions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.push_subscriptions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public access users" ON public.users;
CREATE POLICY "Public access users" ON public.users FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public access matches" ON public.matches;
CREATE POLICY "Public access matches" ON public.matches FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public access predictions" ON public.predictions;
CREATE POLICY "Public access predictions" ON public.predictions FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public access push_subscriptions" ON public.push_subscriptions;
CREATE POLICY "Public access push_subscriptions" ON public.push_subscriptions FOR ALL USING (true) WITH CHECK (true);

